### ISSUE TITLE
Something wrong about GSS realignment from ASR-model

### ISSUE THREAD

**Issue by ft-speech** [fgnt/pb_chime5#22]
Hello,
When i run  activity_alignment.py(Generate finetuned time annotations from kaldi worn alignments), there is something wrong ，The following information is an error message：

Warning: Could not find P08_S02-0883960-0884024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0887758-0888024 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Warning: Could not find P08_S02-0889164-0889316 in non_sil_alignment.
Traceback (most recent call last):
  File "activity_alignment.py", line 198, in <module>
    use_ArrayIntervall=True,
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/activity.py", line 214, in get_activity
    f'Something went wrong.\n'
RuntimeError: Something went wrong.
Expected 22932 times a finetuned annotation for session S02, but 22932 times they are missing.
Expect that at least 1911 finetuned annotations are available, when non_sil_alignment_fn is given.
Otherwise assume something went wrong.

Thanks a lot if you can answer how to avoid this mistake

**Comment by jensheit** [comment]
Hi,
it looks like you are trying to run the activity_alignment.py file. This is not recommended since the `__main__` function uses a hard-coded path to our kaldi environment.
You can use the  `__main__` function to get an idea how to use the  get_non_sil_alignment_fn_from_kalid function that is provided in this file.

Of course you have to setup a kaldi environment and calculate the alignments in Kaldi if you want to use this function.

Hope this helps

**Comment by ft-speech** [comment]
> Hi, it looks like you are trying to run the activity_alignment.py file. This is not recommended since the `__main__` function uses a hard-coded path to our kaldi environment. You can use the `__main__` function to get an idea how to use the get_non_sil_alignment_fn_from_kalid function that is provided in this file.
> 
> Of course you have to setup a kaldi environment and calculate the alignments in Kaldi if you want to use this function.
> 
> Hope this helps


Thank you very much for your answer. I have solved this problem, but I have another problem ：

ERROR - Chime5 Array Enhancement - Failed after 1 day, 10:27:41!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/scripts/run.py", line 91, in main
    run(_run)
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/scripts/run.py", line 128, in run
    audio_dir_exist_ok=True
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 381, in enhance_session
    x_hat = self.enhance_example(ex)
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 495, in enhance_example
    debug=debug,
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 533, in enhance_observation
    masks = self.gss_block(Obs, acitivity_freq, debug=debug)
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 183, in __call__
    source_activity_mask=source_active_mask[f, ..., :T],
  File "/kaldi/egs/chime6/pb_chime5/pb_chime5/pb_bss/pb_bss/distribution/cacgmm.py", line 223, in fit
    initialization.shape, affiliation_shape
AssertionError: ((5, 1140), (5, 1165))
# Accounting: time=124068 threads=1

Do you know what I should do to solve this problem？

**Comment by ft-speech** [comment]
> Hi, it looks like you are trying to run the activity_alignment.py file. This is not recommended since the `__main__` function uses a hard-coded path to our kaldi environment. You can use the `__main__` function to get an idea how to use the get_non_sil_alignment_fn_from_kalid function that is provided in this file.
> 
> Of course you have to setup a kaldi environment and calculate the alignments in Kaldi if you want to use this function.
> 
> Hope this helps

Thank you very much for your answer. I have solved this problem, but I have another problem ：

ERROR - Chime5 Array Enhancement - Failed after 1 day, 10:27:41!
Traceback (most recent calls WITHOUT Sacred internals):
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/scripts/run.py", line 91, in main
run(_run)
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/scripts/run.py", line 128, in run
audio_dir_exist_ok=True
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 381, in enhance_session
x_hat = self.enhance_example(ex)
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 495, in enhance_example
debug=debug,
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 533, in enhance_observation
masks = self.gss_block(Obs, acitivity_freq, debug=debug)
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/core_chime6.py", line 183, in call
source_activity_mask=source_active_mask[f, ..., :T],
File "/kaldi/egs/chime6/pb_chime5/pb_chime5/pb_bss/pb_bss/distribution/cacgmm.py", line 223, in fit
initialization.shape, affiliation_shape
AssertionError: ((5, 1140), (5, 1165))

Do you know what I should do to solve this problem
